from graphviz import Source
import os

os.environ["PATH"] += os.pathsep + r"C:\Program Files\Graphviz\bin"
dot_code = """

strict digraph {
nd -> fs [label=FF]
ql -> qz [label=FF]
gz -> vv [label=FF]
lg -> zx [label=FF]
lg -> lx [label=FF]
tr -> sd [label=FF]
vn -> ql [label=FF]
vn -> qz [label=FF]
kg -> xz [label=FF]
sj -> gs [label=FF]
bq -> rx [label=CO]
hf -> xm [label=FF]
vv -> mq [label=FF]
vv -> db [label=FF]
gf -> fn [label=FF]
gf -> lx [label=FF]
zt -> sk [label=FF]
bm -> lx [label=FF]
bm -> cp [label=FF]
cp -> lx [label=FF]
cp -> gb [label=FF]
gs -> gq [label=FF]
gs -> qz [label=FF]
sp -> db [label=FF]
sp -> jh [label=FF]
bh -> kr [label=FF]
bh -> db [label=FF]
xb -> qz [label=FF]
xb -> vn [label=FF]
fx -> qf [label=FF]
gq -> qz [label=FF]
gq -> xb [label=FF]
xp -> zn [label=FF]
xp -> sd [label=FF]
hl -> tr [label=FF]
hl -> sd [label=FF]
sk -> nd [label=FF]
mh -> xs [label=FF]
mh -> sd [label=FF]
qz -> nd [label=CO]
qz -> sj [label=CO]
qz -> sk [label=CO]
qz -> gp [label=CO]
qz -> gc [label=CO]
qz -> vh [label=CO]
qz -> zt [label=CO]
vg -> bq [label=CO]
sh -> pz [label=FF]
jh -> kg [label=FF]
kp -> bq [label=CO]
gp -> zt [label=FF]
gc -> bq [label=CO]
xf -> xp [label=FF]
cv -> sd [label=FF]
cv -> hl [label=FF]
db -> kg [label=CO]
db -> sp [label=CO]
db -> kp [label=CO]
db -> fx [label=CO]
db -> jh [label=CO]
db -> gz [label=CO]
kr -> db [label=FF]
xz -> zs [label=FF]
xz -> db [label=FF]
fs -> qz [label=FF]
fs -> sj [label=FF]
xm -> kh [label=FF]
xm -> lx [label=FF]
qf -> db [label=FF]
qf -> gz [label=FF]
fn -> bm [label=FF]
kh -> lx [label=FF]
kh -> gf [label=FF]
vh -> qz [label=FF]
vh -> gp [label=FF]
mq -> bh [label=FF]
mq -> db [label=FF]
zn -> cv [label=FF]
sv -> xf [label=FF]
sv -> sd [label=FF]
lh -> lx [label=FF]
dl -> lh [label=FF]
dl -> lx [label=FF]
zx -> lx [label=FF]
zx -> hf [label=FF]
pz -> sd [label=FF]
pz -> cn [label=FF]
cn -> sd [label=FF]
cn -> sv [label=FF]
xs -> sh [label=FF]
gb -> lx [label=FF]
gb -> dl [label=FF]
tx -> bq [label=CO]
sd -> mh [label=CO]
sd -> tx [label=CO]
sd -> sh [label=CO]
sd -> xf [label=CO]
sd -> zn [label=CO]
sd -> xs [label=CO]
lx -> fn [label=CO]
lx -> hf [label=CO]
lx -> vg [label=CO]
lx -> lg [label=CO]
zs -> db [label=FF]
zs -> fx [label=FF]
broadcaster -> vh [label=br]
broadcaster -> sp [label=br]
broadcaster -> lg [label=br]
broadcaster -> mh [label=br]
}
"""

swaps = []
swaps.append(("hdt", "z05"))


source = Source(dot_code)
source.render("graph_output", format="png", view=True)
